# yazi.toml
[mgr]
ratio = [1,3,4]
sort_by        = "alphabetical"
sort_sensitive = false
sort_reverse 	 = false
sort_dir_first = true
sort_translit  = false
linemode       = "none"
show_hidden    = true
show_symlink   = true
scrolloff      = 5
mouse_events   = [ "click", "scroll" ]
title_format   = "Yazi: {cwd}"

[opener]
edit = [
    { run = 'nvim "$@"', block = true },
]

play = [
	{ run = 'mpv "$@"', orphan = true, for = "unix" },
]

# [[opener.set-wallpaper]]
# run  = 'swww img ,"$0"'
# for  = "linux"
# desc = "Set as wallpaper"
# [[open.prepend_rules]]
# mime = "image/*"
# use  = [ "set-wallpaper", "open" ]

[preview]
max_width = 1000

[plugin]
prepend_previewers = [
  { name = "*.md", run = "glow" },
]
