# yazi.toml

[mgr]
ratio           = [1,3,4]
sort_by         = "alphabetical"
sort_sensitive  = false
sort_reverse    = false
sort_dir_first  = true
sort_translit   = false
linemode        = "none"
show_hidden     = true
show_symlink    = true
scrolloff       = 5
mouse_events    = ["click", "scroll"]
title_format    = "Yazi: {cwd}"

[opener]
edit = [
    { run = 'nvim "$@"', block = true },
]

play = [
    { run = 'mpv "$@"', orphan = true, for = "unix" },
]

[preview]
max_width = 1000

[plugin]

prepend_preloaders = [
    { mime = "{audio,video,image}/*", run = "mediainfo" },
    { mime = "application/subrip", run = "mediainfo" },

    { mime = "{application/postscript,application/illustrator,application/vnd.adobe.illustrator,image/x-eps,application/eps}", run = "mediainfo" },

    { url = "*.{ai,eps,ait}", run = "mediainfo" },

    { mime = "{image}/*", run = "mediainfo --no-metadata" },
    { mime = "{video}/*", run = "mediainfo --no-preview" },
]

prepend_previewers = [

    # Markdown
	{ url = "*.md", run = 'piper -- CLICOLOR_FORCE=1 glow -w=$w -s=dark "$1"'},

    # CSV
    { mime = "text/csv", run = 'piper -- bat -p --color=always "$1"' },

    # Archives
    { url = "*.tar*", run = 'piper --format=url -- tar tf "$1"' },

    # Directory tree
    { url = "*/", run = 'piper -- eza -TL=3 --color=always --icons=always --group-directories-first --no-quotes "$1"' },

    # MediaInfo previews
    { mime = "{audio,video,image}/*", run = "mediainfo" },
    { mime = "application/subrip", run = "mediainfo" },

    { mime = "application/postscript", run = "mediainfo" },
    { mime = "application/illustrator", run = "mediainfo" },
    { mime = "application/dvb.ait", run = "mediainfo" },
    { mime = "application/vnd.adobe.illustrator", run = "mediainfo" },
    { mime = "image/x-eps", run = "mediainfo" },
    { mime = "application/eps", run = "mediainfo" },

    { url = "*.{ai,eps,ait}", run = "mediainfo" },

    { mime = "{image}/*", run = "mediainfo --no-metadata" },
    { mime = "{video}/*", run = "mediainfo --no-preview" },
]

append_previewers = [

    # Hex fallback
    { url = "*", run = 'piper -- hexyl --border=none --terminal-width=$w "$1"' },
]

[tasks]
image_alloc = 1073741824
