# yazi.toml
[manager]
show_hidden = true
ratio = [1,3,4]

[opener]
edit = [
    { run = 'nvim "$@"', block = true },
]

play = [
	{ run = 'mpv "$@"', orphan = true, for = "unix" },
]

[plugin]
prepend_previewers = [
  { name = "*.md", run = "glow" },
]
