#!/bin/bash

red='\033[0;31m'
nocolor='\033[0m'

gum confirm " restart pipewire & wireplumber? " && systemctl --user restart pipewire pipewire-pulse wireplumber

exit_code=$?

if [[ 0 -eq $exit_code ]]; then
	echo "Sucessfully restarted pipewire, pipewire-pulse, and wireplumber"
else
	echo -e "${red}ERROR:${nocolor} Failed to restart services"
fi
