#!/usr/bin/bash

if ! find . -maxdepth 1 -type f | read; then
	echo "Empty directory"
	exit 1
fi

if [[ $# < 2 ]] ; then 
	liststart=1
	liststop=$1
fi


# if [[ $3 -eq 1 ]];then
# 	mpv $(printf " *%03d.*" $(seq $1 $2))
# 	exit
# fi


mpv $(printf " *%02d.*" $(seq $1 $2))
